import type { Quest } from "../types";

export const quest1: Quest = {
  id: "finding-customers",
  name: "Finding Customers",
  description: "Discover potential customers using our powerful AI search tools.",
  emoji: "🔍",
  challenges: [
    {
      id: "basic-company-contact-search",
      name: "Basic Company & Contact Search",
      description: "Perform your first company and contacts search",
      emoji: "🎯",
      trigger: {
        type: "newUser",
        route: "/app",
        requiresAuth: true,
        once: true,
      },
      startDelay: 7000,
      setupEvent: "startNewSearch",
      steps: [
        {
          id: "open-search-options",
          selector: '[data-testid="search-options-button"]',
          action: "click",
          instruction: "Click on the search options to choose what you want to search for",
          tooltipPosition: "bottom",
          route: "/app",
        },
        {
          id: "select-contacts-search",
          selector: '[data-testid="search-type-option-contacts"]',
          action: "click",
          instruction: "Select '+ Contacts' to search for companies AND their contacts",
          tooltipPosition: "bottom",
          route: "/app",
        },
        {
          id: "search-input",
          selector: '[data-testid="search-input"]',
          action: "click",
          instruction: "Click on the search bar to start.",
          tooltipPosition: "bottom",
          route: "/app",
        },
        {
          id: "type-query",
          selector: '[data-testid="search-input"]',
          action: "type",
          advanceDelay: 3000,
          instruction: "Type a search query like 'marketing agencies in Austin'.",
          tooltipPosition: "bottom",
          route: "/app",
        },
        {
          id: "execute-search",
          selector: '[data-testid="search-button"]',
          action: "click",
          instruction: "Click on Search!",
          tooltipPosition: "left",
          route: "/app",
        },
      ],
      completionMessage: "Awesome! You've completed your first search! 🎉",
    },
    {
      id: "custom-role-search",
      name: "Custom Role Search",
      description: "Search for contacts with specific roles at companies",
      emoji: "👤",
      steps: [],
      completionMessage: "Great! You've learned how to search for specific roles! 🎯",
    },
    {
      id: "find-email-unique-contact",
      name: "Find Email of Unique Contact",
      description: "Use the email finder to discover a specific contact's email",
      emoji: "📧",
      steps: [],
      completionMessage: "Excellent! You've discovered how to find contact emails! 📬",
    },
    {
      id: "full-search",
      name: "Do a Full Search",
      description: "Complete a full search with contacts and emails in one go",
      emoji: "🚀",
      steps: [],
      completionMessage: "Congratulations! You've mastered the complete search workflow! 🎉",
    },
  ],
};
