// Static mock contacts for test emails - always use the same data
export const mockContactsForTesting = [
  {
    id: 1,
    batchId: 0,
    contactId: 1,
    companyId: 1,
    emailSubject: 'Streamline Your Engineering Workflow',
    emailBody: 'Sample email content...',
    status: 'pending' as const,
    createdAt: new Date(),
    contact: {
      id: 1,
      userId: 1,
      companyId: 1,
      name: 'Sarah Johnson',
      role: 'VP of Engineering',
      email: 'sarah@techcorp.example',
      alternativeEmails: [],
      probability: null,
      linkedinUrl: null,
      twitterHandle: null,
      phoneNumber: null,
      department: null,
      location: null,
      verificationSource: null,
      lastEnriched: null,
      nameConfidenceScore: 95,
      emailConfidenceScore: 95,
      userFeedbackScore: null,
      feedbackCount: 0,
      lastValidated: null,
      createdAt: new Date(),
      completedSearches: [],
      contactStatus: 'uncontacted' as const,
      lastContactedAt: null,
      lastContactChannel: null,
      totalCommunications: 0,
      totalReplies: 0,
      lastThreadId: null
    },
    company: {
      id: 1,
      userId: 1,
      listId: 1,
      name: 'TechCorp Solutions',
      website: 'https://techcorp.example',
      description: 'Leading technology solutions provider',
      age: null,
      size: null,
      alternativeProfileUrl: null,
      defaultContactEmail: null,
      ranking: null,
      linkedinProminence: null,
      customerCount: null,
      rating: null,
      services: [],
      validationPoints: [],
      differentiation: [],
      totalScore: null,
      snapshot: {},
      createdAt: new Date()
    }
  },
  {
    id: 2,
    batchId: 0,
    contactId: 2,
    companyId: 2,
    emailSubject: 'Boost Your Product Innovation',
    emailBody: 'Sample email content...',
    status: 'pending' as const,
    createdAt: new Date(),
    contact: {
      id: 2,
      userId: 1,
      companyId: 2,
      name: 'Michael Chen',
      role: 'Director of Product',
      email: 'mchen@innovatelabs.example',
      alternativeEmails: [],
      probability: null,
      linkedinUrl: null,
      twitterHandle: null,
      phoneNumber: null,
      department: null,
      location: null,
      verificationSource: null,
      lastEnriched: null,
      nameConfidenceScore: 95,
      emailConfidenceScore: 95,
      userFeedbackScore: null,
      feedbackCount: 0,
      lastValidated: null,
      createdAt: new Date(),
      completedSearches: [],
      contactStatus: 'uncontacted' as const,
      lastContactedAt: null,
      lastContactChannel: null,
      totalCommunications: 0,
      totalReplies: 0,
      lastThreadId: null
    },
    company: {
      id: 2,
      userId: 1,
      listId: 1,
      name: 'Innovate Labs',
      website: 'https://innovatelabs.example',
      description: 'Innovation consulting and development',
      age: null,
      size: null,
      alternativeProfileUrl: null,
      defaultContactEmail: null,
      ranking: null,
      linkedinProminence: null,
      customerCount: null,
      rating: null,
      services: [],
      validationPoints: [],
      differentiation: [],
      totalScore: null,
      snapshot: {},
      createdAt: new Date()
    }
  },
  {
    id: 3,
    batchId: 0,
    contactId: 3,
    companyId: 3,
    emailSubject: 'Transform Your Marketing Strategy',
    emailBody: 'Sample email content...',
    status: 'pending' as const,
    createdAt: new Date(),
    contact: {
      id: 3,
      userId: 1,
      companyId: 3,
      name: 'Emily Rodriguez',
      role: 'CMO',
      email: 'emily.r@growthdigital.example',
      alternativeEmails: [],
      probability: null,
      linkedinUrl: null,
      twitterHandle: null,
      phoneNumber: null,
      department: null,
      location: null,
      verificationSource: null,
      lastEnriched: null,
      nameConfidenceScore: 95,
      emailConfidenceScore: 95,
      userFeedbackScore: null,
      feedbackCount: 0,
      lastValidated: null,
      createdAt: new Date(),
      completedSearches: [],
      contactStatus: 'uncontacted' as const,
      lastContactedAt: null,
      lastContactChannel: null,
      totalCommunications: 0,
      totalReplies: 0,
      lastThreadId: null
    },
    company: {
      id: 3,
      userId: 1,
      listId: 1,
      name: 'Growth Digital Agency',
      website: 'https://growthdigital.example',
      description: 'Digital marketing and growth strategies',
      age: null,
      size: null,
      alternativeProfileUrl: null,
      defaultContactEmail: null,
      ranking: null,
      linkedinProminence: null,
      customerCount: null,
      rating: null,
      services: [],
      validationPoints: [],
      differentiation: [],
      totalScore: null,
      snapshot: {},
      createdAt: new Date()
    }
  },
  {
    id: 4,
    batchId: 0,
    contactId: 4,
    companyId: 4,
    emailSubject: 'Optimize Your Data Infrastructure',
    emailBody: 'Sample email content...',
    status: 'pending' as const,
    createdAt: new Date(),
    contact: {
      id: 4,
      userId: 1,
      companyId: 4,
      name: 'David Kim',
      role: 'Head of Data Science',
      email: 'dkim@datainsights.example',
      alternativeEmails: [],
      probability: null,
      linkedinUrl: null,
      twitterHandle: null,
      phoneNumber: null,
      department: null,
      location: null,
      verificationSource: null,
      lastEnriched: null,
      nameConfidenceScore: 95,
      emailConfidenceScore: 95,
      userFeedbackScore: null,
      feedbackCount: 0,
      lastValidated: null,
      createdAt: new Date(),
      completedSearches: [],
      contactStatus: 'uncontacted' as const,
      lastContactedAt: null,
      lastContactChannel: null,
      totalCommunications: 0,
      totalReplies: 0,
      lastThreadId: null
    },
    company: {
      id: 4,
      userId: 1,
      listId: 1,
      name: 'DataInsights Co',
      website: 'https://datainsights.example',
      description: 'Advanced analytics and data solutions',
      age: null,
      size: null,
      alternativeProfileUrl: null,
      defaultContactEmail: null,
      ranking: null,
      linkedinProminence: null,
      customerCount: null,
      rating: null,
      services: [],
      validationPoints: [],
      differentiation: [],
      totalScore: null,
      snapshot: {},
      createdAt: new Date()
    }
  },
  {
    id: 5,
    batchId: 0,
    contactId: 5,
    companyId: 5,
    emailSubject: 'Enhance Your Customer Experience',
    emailBody: 'Sample email content...',
    status: 'pending' as const,
    createdAt: new Date(),
    contact: {
      id: 5,
      userId: 1,
      companyId: 5,
      name: 'Jessica Thompson',
      role: 'Director of Operations',
      email: 'jthompson@nexusventures.example',
      alternativeEmails: [],
      probability: null,
      linkedinUrl: null,
      twitterHandle: null,
      phoneNumber: null,
      department: null,
      location: null,
      verificationSource: null,
      lastEnriched: null,
      nameConfidenceScore: 95,
      emailConfidenceScore: 95,
      userFeedbackScore: null,
      feedbackCount: 0,
      lastValidated: null,
      createdAt: new Date(),
      completedSearches: [],
      contactStatus: 'uncontacted' as const,
      lastContactedAt: null,
      lastContactChannel: null,
      totalCommunications: 0,
      totalReplies: 0,
      lastThreadId: null
    },
    company: {
      id: 5,
      userId: 1,
      listId: 1,
      name: 'Nexus Ventures',
      website: 'https://nexusventures.example',
      description: 'Venture capital and business development',
      age: null,
      size: null,
      alternativeProfileUrl: null,
      defaultContactEmail: null,
      ranking: null,
      linkedinProminence: null,
      customerCount: null,
      rating: null,
      services: [],
      validationPoints: [],
      differentiation: [],
      totalScore: null,
      snapshot: {},
      createdAt: new Date()
    }
  }
];